import React, { useState } from "react";
import { Button } from "../ui/button.jsx";
import { Badge } from "../ui/badge.jsx";
import { Card, CardHeader, CardContent } from "../ui/card.jsx";
import { GithubIcon as Github } from "../ui/githubIcon.jsx";
import { ArrowRight, Webhook, Code2, GitCommit, Sparkles, Check, Copy, CheckCircle2, FileText, Database, Shield, Zap, Layers } from "lucide-react";

const AUTHKIT_WIDGET_TABS = [
    {
        id: "routes",
        label: "AST Route Extractor",
        icon: Code2,
        title: "Express & Fastify Route AST Parsing",
        desc: "Deterministically parses URL parameters, HTTP verbs, and controller middleware directly from code AST.",
        renderPreview: () => (
            <div className="space-y-3 font-mono text-xs">
                <div className="flex items-center justify-between text-muted-foreground border-b border-border pb-2">
                    <span>Parsed AST Route Endpoint</span>
                    <span className="text-emerald-500 font-semibold">GET /api/v1/users/:id</span>
                </div>
                <div className="p-3 bg-muted/40 rounded-md border border-border space-y-1.5 text-[11px]">
                    <div className="text-primary font-semibold">// Controller Handler</div>
                    <div className="text-foreground">Controller: getUserByIdHandler</div>
                    <div className="text-muted-foreground">Middleware: [authenticateToken, checkRateLimit]</div>
                    <div className="text-muted-foreground">URL Params: id (string, required)</div>
                </div>
                <div className="flex items-center gap-2 text-emerald-500 text-[11px] font-sans font-medium">
                    <CheckCircle2 className="h-3.5 w-3.5" />
                    <span>Extracted with 100% ground-truth accuracy from @babel/parser</span>
                </div>
            </div>
        ),
    },
    {
        id: "schemas",
        label: "Schema Model Parser",
        icon: Database,
        title: "Mongoose & Prisma Model Extraction",
        desc: "Extracts database schema fields, field validation rules, and relational definitions automatically.",
        renderPreview: () => (
            <div className="space-y-3 font-mono text-xs">
                <div className="flex items-center justify-between text-muted-foreground border-b border-border pb-2">
                    <span>Target Schema</span>
                    <span className="text-primary font-semibold">UserSchema (Mongoose)</span>
                </div>
                <div className="grid grid-cols-2 gap-2 text-[11px]">
                    <div className="p-2.5 bg-muted/40 rounded border border-border">
                        <span className="text-foreground font-semibold">email:</span> <span className="text-muted-foreground">String (Required, Unique)</span>
                    </div>
                    <div className="p-2.5 bg-muted/40 rounded border border-border">
                        <span className="text-foreground font-semibold">role:</span> <span className="text-muted-foreground">Enum ["admin", "user"]</span>
                    </div>
                    <div className="p-2.5 bg-muted/40 rounded border border-border">
                        <span className="text-foreground font-semibold">passwordHash:</span> <span className="text-muted-foreground">String (Select: false)</span>
                    </div>
                    <div className="p-2.5 bg-muted/40 rounded border border-border">
                        <span className="text-foreground font-semibold">createdAt:</span> <span className="text-muted-foreground">Date (Default: Date.now)</span>
                    </div>
                </div>
            </div>
        ),
    },
    {
        id: "readme",
        label: "Auto README Sync",
        icon: FileText,
        title: "Direct Commit back to Repository",
        desc: "Formats clean, structured Markdown documentation and dispatches git commits back to your default branch.",
        renderPreview: () => (
            <div className="space-y-3 font-sans text-xs">
                <div className="flex items-center justify-between border-b border-border pb-2">
                    <span className="font-bold text-foreground"># API Reference & Documentation</span>
                    <Badge variant="secondary" className="font-mono text-[10px]">README.md</Badge>
                </div>
                <p className="text-muted-foreground text-xs leading-relaxed">
                    Automated documentation generated by PushDoc AI engine based on commit <code className="bg-muted px-1.5 py-0.5 rounded font-mono text-[10px]">#7dfae20</code>.
                </p>
                <div className="p-3 bg-muted/30 rounded border border-border space-y-1 text-[11px] font-mono">
                    <div className="text-emerald-500 font-semibold">✓ Committed to origin/main</div>
                    <div className="text-muted-foreground">Author: PushDoc Bot &lt;bot@pushdoc.io&gt;</div>
                </div>
            </div>
        ),
    },
    {
        id: "badges",
        label: "Shields.io Audit",
        icon: Shield,
        title: "Dependency & Status Badge Generation",
        desc: "Audits package.json dependencies to generate confirmed Shields.io tech badges without dead links.",
        renderPreview: () => (
            <div className="space-y-3 font-sans text-xs">
                <div className="text-muted-foreground text-xs">Verified Repository Tech Badges:</div>
                <div className="flex flex-wrap gap-2 pt-1">
                    <span className="px-2.5 py-1 bg-blue-500/10 text-blue-400 border border-blue-500/30 rounded font-mono text-[11px]">Express v4.19</span>
                    <span className="px-2.5 py-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 rounded font-mono text-[11px]">Node.js v20</span>
                    <span className="px-2.5 py-1 bg-purple-500/10 text-purple-400 border border-purple-500/30 rounded font-mono text-[11px]">MongoDB v6.0</span>
                    <span className="px-2.5 py-1 bg-amber-500/10 text-amber-400 border border-amber-500/30 rounded font-mono text-[11px]">Shields.io Verified</span>
                </div>
            </div>
        ),
    },
];

export default function Hero({ handleLoginRedirect, setPage }) {
    const [copied, setCopied] = useState(false);
    const [activeTabId, setActiveTabId] = useState("routes");

    const activeTab = AUTHKIT_WIDGET_TABS.find(t => t.id === activeTabId) || AUTHKIT_WIDGET_TABS[0];

    const handleCopy = () => {
        navigator.clipboard.writeText("npx pushdoc@latest sync");
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <section className="relative pt-36 pb-28 overflow-hidden bg-background text-foreground">
            {/* AuthKit Ambient Motion Glow */}
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1100px] h-[550px] bg-gradient-to-b from-primary/15 via-primary/5 to-transparent blur-[140px] pointer-events-none -z-0" />

            <div className="max-w-7xl mx-auto px-6 relative z-10 text-center">
                {/* AuthKit Announcement pill */}
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-border bg-card/70 backdrop-blur-md text-xs mb-8 shadow-sm transition-transform hover:scale-105">
                    <Sparkles className="h-3.5 w-3.5 text-primary animate-spin" />
                    <span className="text-foreground font-semibold">Introducing PushDoc 2.0</span>
                    <span className="text-muted-foreground font-normal">• The Developer Documentation Platform</span>
                </div>

                {/* Exact Headline Copy Requested */}
                <h1 className="text-5xl sm:text-7xl lg:text-8xl font-black tracking-tight text-foreground max-w-5xl mx-auto leading-[1.04] text-balance">
                    Your Codebase.<br />
                    <span className="bg-clip-text text-transparent bg-gradient-to-r from-foreground via-muted-foreground to-foreground/60">
                        Documented on Every Commit.
                    </span>
                </h1>

                {/* Subtitle */}
                <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mt-7 leading-relaxed text-balance font-normal">
                    An AI-powered documentation engine that parses raw AST facts into clean, production-ready READMEs directly from Git.
                </p>

                {/* Action Buttons */}
                <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mt-9">
                    <Button 
                        size="lg" 
                        onClick={() => setPage("connect")}
                        className="gap-2.5 font-semibold rounded-full px-8 h-12 text-sm bg-foreground text-background hover:bg-foreground/90 shadow-xl transition-all transform hover:-translate-y-0.5"
                    >
                        <Github className="h-4 w-4" />
                        <span>Connect Repository</span>
                        <ArrowRight className="h-4 w-4" />
                    </Button>

                    <div className="flex items-center gap-3 bg-card/80 border border-border/80 backdrop-blur-md rounded-full px-5 h-12 font-mono text-xs text-foreground shadow-sm hover:border-primary/50 transition-all">
                        <span className="text-primary">$</span>
                        <span className="tracking-tight">npx pushdoc@latest sync</span>
                        <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7 text-muted-foreground hover:text-foreground transition-colors"
                            onClick={handleCopy}
                        >
                            {copied ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
                        </Button>
                    </div>
                </div>

                {/* AuthKit Style Interactive Live Canvas Widget Component */}
                <div className="mt-16 max-w-4xl mx-auto text-left">
                    <Card className="shadow-2xl border-border bg-card overflow-hidden rounded-2xl">
                        <div className="p-4 border-b border-border bg-muted/40 flex flex-wrap items-center justify-between gap-3">
                            <div className="flex items-center gap-2">
                                <div className="flex gap-1.5 mr-2">
                                    <div className="h-3 w-3 rounded-full bg-destructive/60" />
                                    <div className="h-3 w-3 rounded-full bg-amber-500/60" />
                                    <div className="h-3 w-3 rounded-full bg-emerald-500/60" />
                                </div>
                                <span className="text-xs font-mono text-muted-foreground">Interactive Engine Canvas</span>
                            </div>

                            <div className="flex flex-wrap gap-1.5">
                                {AUTHKIT_WIDGET_TABS.map((tab) => {
                                    const TabIcon = tab.icon;
                                    const isActive = tab.id === activeTabId;
                                    return (
                                        <Button
                                            key={tab.id}
                                            variant={isActive ? "secondary" : "ghost"}
                                            size="sm"
                                            className={`text-xs h-7 px-3 gap-1.5 ${isActive ? "font-semibold shadow-sm" : "text-muted-foreground"}`}
                                            onClick={() => setActiveTabId(tab.id)}
                                        >
                                            <TabIcon className="h-3.5 w-3.5" />
                                            <span>{tab.label}</span>
                                        </Button>
                                    );
                                })}
                            </div>
                        </div>

                        <CardContent className="p-6 space-y-4">
                            <div className="space-y-1">
                                <h3 className="text-sm font-bold text-foreground">{activeTab.title}</h3>
                                <p className="text-xs text-muted-foreground leading-relaxed">{activeTab.desc}</p>
                            </div>

                            <div className="p-4 bg-muted/20 rounded-xl border border-border/80 transition-all duration-300">
                                {activeTab.renderPreview()}
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* AuthKit 3-Bento Card Showcase Row */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto mt-16 text-left">
                    <Card className="bg-card/60 border-border/80 shadow-none hover:border-primary/40 transition-all duration-300 transform hover:-translate-y-1 group rounded-xl">
                        <CardContent className="p-6">
                            <div className="h-10 w-10 rounded-xl bg-muted flex items-center justify-center text-foreground mb-4 border border-border group-hover:border-primary/50 group-hover:bg-primary/10 transition-all">
                                <Webhook className="h-5 w-5" />
                            </div>
                            <h3 className="text-base font-bold text-foreground">Zero-Config Webhooks</h3>
                            <p className="text-xs text-muted-foreground mt-2 leading-relaxed">
                                Fires automatically on git push events with sub-7ms payload parsing and HMAC cryptographic verification.
                            </p>
                        </CardContent>
                    </Card>

                    <Card className="bg-card/60 border-border/80 shadow-none hover:border-primary/40 transition-all duration-300 transform hover:-translate-y-1 group rounded-xl">
                        <CardContent className="p-6">
                            <div className="h-10 w-10 rounded-xl bg-muted flex items-center justify-center text-foreground mb-4 border border-border group-hover:border-primary/50 group-hover:bg-primary/10 transition-all">
                                <Code2 className="h-5 w-5" />
                            </div>
                            <h3 className="text-base font-bold text-foreground">AST Fact Extraction</h3>
                            <p className="text-xs text-muted-foreground mt-2 leading-relaxed">
                                Deterministically parses Express routes, Mongoose schemas, and APIs before AI prompt synthesis to prevent hallucinations.
                            </p>
                        </CardContent>
                    </Card>

                    <Card className="bg-card/60 border-border/80 shadow-none hover:border-primary/40 transition-all duration-300 transform hover:-translate-y-1 group rounded-xl">
                        <CardContent className="p-6">
                            <div className="h-10 w-10 rounded-xl bg-muted flex items-center justify-center text-foreground mb-4 border border-border group-hover:border-primary/50 group-hover:bg-primary/10 transition-all">
                                <GitCommit className="h-5 w-5" />
                            </div>
                            <h3 className="text-base font-bold text-foreground">Auto README Sync</h3>
                            <p className="text-xs text-muted-foreground mt-2 leading-relaxed">
                                Commits clean, structured README markdown directly back to your default branch or pull request automatically.
                            </p>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </section>
    );
}
