import React, { useState } from "react";
import { Button } from "../ui/button.jsx";
import { Badge } from "../ui/badge.jsx";
import { Card, CardHeader, CardContent } from "../ui/card.jsx";
import { GithubIcon as Github } from "../ui/githubIcon.jsx";
import { ArrowRight, Webhook, Code2, GitCommit, Sparkles, Check, Copy, CheckCircle2, FileText, Database, Shield, Zap, Layers } from "lucide-react";

const AUTHKIT_WIDGET_TABS = [
    {
        id: "routes",
        label: "AST Route Extractor",
        icon: Code2,
        title: "Express & Fastify Route AST Parsing",
        desc: "Deterministically parses URL parameters, HTTP verbs, and controller middleware directly from code AST.",
        renderPreview: () => (
            <div className="space-y-3 font-mono text-xs">
                <div className="flex items-center justify-between text-text-secondary border-b border-border pb-2">
                    <span>Parsed AST Route Endpoint</span>
                    <span className="text-success font-semibold">GET /api/v1/users/:id</span>
                </div>
                <div className="p-3 bg-surface-raised rounded-[6px] space-y-1.5 text-xs">
                    <div className="text-accent font-semibold">// Controller Handler</div>
                    <div className="text-text-primary">Controller: getUserByIdHandler</div>
                    <div className="text-text-secondary">Middleware: [authenticateToken, checkRateLimit]</div>
                    <div className="text-text-secondary">URL Params: id (string, required)</div>
                </div>
                <div className="flex items-center gap-2 text-success text-xs font-sans font-medium">
                    <CheckCircle2 className="h-3.5 w-3.5" />
                    <span>Extracted with 100% ground-truth accuracy from @babel/parser</span>
                </div>
            </div>
        ),
    },
    {
        id: "schemas",
        label: "Schema Model Parser",
        icon: Database,
        title: "Mongoose & Prisma Model Extraction",
        desc: "Extracts database schema fields, field validation rules, and relational definitions automatically.",
        renderPreview: () => (
            <div className="space-y-3 font-mono text-xs">
                <div className="flex items-center justify-between text-text-secondary border-b border-border pb-2">
                    <span>Target Schema</span>
                    <span className="text-accent font-semibold">UserSchema (Mongoose)</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                    <div className="p-2.5 bg-surface-raised rounded-[6px]">
                        <span className="text-text-primary font-semibold">email:</span> <span className="text-text-secondary">String (Required, Unique)</span>
                    </div>
                    <div className="p-2.5 bg-surface-raised rounded-[6px]">
                        <span className="text-text-primary font-semibold">role:</span> <span className="text-text-secondary">Enum ["admin", "user"]</span>
                    </div>
                    <div className="p-2.5 bg-surface-raised rounded-[6px]">
                        <span className="text-text-primary font-semibold">passwordHash:</span> <span className="text-text-secondary">String (Select: false)</span>
                    </div>
                    <div className="p-2.5 bg-surface-raised rounded-[6px]">
                        <span className="text-text-primary font-semibold">createdAt:</span> <span className="text-text-secondary">Date (Default: Date.now)</span>
                    </div>
                </div>
            </div>
        ),
    },
    {
        id: "readme",
        label: "Auto README Sync",
        icon: FileText,
        title: "Direct Commit back to Repository",
        desc: "Formats clean, structured Markdown documentation and dispatches git commits back to your default branch.",
        renderPreview: () => (
            <div className="space-y-3 font-sans text-xs">
                <div className="flex items-center justify-between border-b border-border pb-2">
                    <span className="font-semibold text-text-primary"># API Reference & Documentation</span>
                    <Badge variant="secondary" className="font-mono text-xs">README.md</Badge>
                </div>
                <p className="text-text-secondary text-xs leading-relaxed">
                    Automated documentation generated by PushDoc AI engine based on commit <code className="bg-surface-raised px-1.5 py-0.5 rounded-[4px] font-mono text-xs text-text-primary">#7dfae20</code>.
                </p>
                <div className="p-3 bg-surface-raised rounded-[6px] space-y-1 text-xs font-mono">
                    <div className="text-success font-semibold">✓ Committed to origin/main</div>
                    <div className="text-text-secondary">Author: PushDoc Bot &lt;bot@pushdoc.io&gt;</div>
                </div>
            </div>
        ),
    },
    {
        id: "badges",
        label: "Shields.io Audit",
        icon: Shield,
        title: "Dependency & Status Badge Generation",
        desc: "Audits package.json dependencies to generate confirmed Shields.io tech badges without dead links.",
        renderPreview: () => (
            <div className="space-y-3 font-sans text-xs">
                <div className="text-text-secondary text-xs">Verified Repository Tech Badges:</div>
                <div className="flex flex-wrap gap-2 pt-1">
                    <Badge variant="accent" className="font-mono text-xs">Express v4.19</Badge>
                    <Badge variant="success" className="font-mono text-xs">Node.js v20</Badge>
                    <Badge variant="secondary" className="font-mono text-xs">MongoDB v6.0</Badge>
                    <Badge variant="warning" className="font-mono text-xs">Shields.io Verified</Badge>
                </div>
            </div>
        ),
    },
];

export default function Hero({ handleLoginRedirect, setPage }) {
    const [copied, setCopied] = useState(false);
    const [activeTabId, setActiveTabId] = useState("routes");

    const activeTab = AUTHKIT_WIDGET_TABS.find(t => t.id === activeTabId) || AUTHKIT_WIDGET_TABS[0];

    const handleCopy = () => {
        navigator.clipboard.writeText("npx pushdoc@latest sync");
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <section className="relative pt-24 pb-16 bg-bg text-text-primary font-sans">
            <div className="max-w-5xl mx-auto px-6 text-center space-y-6">
                {/* Announcement chip */}
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-[4px] bg-surface-raised text-xs font-mono">
                    <span className="h-2 w-2 rounded-full bg-accent" />
                    <span className="text-text-primary font-medium">PushDoc 2.0</span>
                    <span className="text-text-muted">• Automated Documentation Engine</span>
                </div>

                {/* Headline: IBM Plex Sans 600, 36px scale */}
                <h1 className="text-2xl sm:text-2xl font-semibold tracking-tight text-text-primary max-w-3xl mx-auto leading-tight">
                    Your Codebase. Documented on Every Commit.
                </h1>

                {/* Subtitle */}
                <p className="text-sm sm:text-base text-text-secondary max-w-xl mx-auto leading-relaxed">
                    An AI-powered documentation engine that parses raw AST facts into clean, production-ready READMEs directly from Git.
                </p>

                {/* Action Controls */}
                <div className="flex flex-col sm:flex-row items-center justify-center gap-3 pt-2">
                    <Button 
                        size="lg" 
                        onClick={() => setPage("connect")}
                        className="gap-2 font-medium rounded-[6px] px-6 h-10 text-sm"
                    >
                        <Github className="h-4 w-4" />
                        <span>Connect Repository</span>
                        <ArrowRight className="h-4 w-4" />
                    </Button>

                    <div className="flex items-center gap-2 bg-surface-raised rounded-[6px] px-4 h-10 font-mono text-xs text-text-primary">
                        <span className="text-accent">$</span>
                        <span>npx pushdoc@latest sync</span>
                        <Button
                            variant="ghost"
                            size="icon"
                            className="h-6 w-6 text-text-muted hover:text-text-primary ml-1"
                            onClick={handleCopy}
                        >
                            {copied ? <Check className="h-3.5 w-3.5 text-success" /> : <Copy className="h-3.5 w-3.5" />}
                        </Button>
                    </div>
                </div>

                {/* Interactive Live Canvas Widget */}
                <div className="mt-12 text-left">
                    <Card className="bg-surface rounded-[6px] overflow-hidden">
                        <div className="p-3 border-b border-border bg-surface-raised flex flex-wrap items-center justify-between gap-3">
                            <div className="flex items-center gap-2">
                                <span className="h-2 w-2 rounded-full bg-accent" />
                                <span className="text-xs font-mono font-medium text-text-secondary">AST Engine Inspector</span>
                            </div>

                            <div className="flex flex-wrap gap-1">
                                {AUTHKIT_WIDGET_TABS.map((tab) => {
                                    const TabIcon = tab.icon;
                                    const isActive = tab.id === activeTabId;
                                    return (
                                        <Button
                                            key={tab.id}
                                            variant={isActive ? "secondary" : "ghost"}
                                            size="sm"
                                            className={`text-xs h-6 px-2.5 rounded-[4px] gap-1.5 ${isActive ? "bg-surface text-text-primary font-semibold" : "text-text-secondary"}`}
                                            onClick={() => setActiveTabId(tab.id)}
                                        >
                                            <TabIcon className="h-3.5 w-3.5" />
                                            <span>{tab.label}</span>
                                        </Button>
                                    );
                                })}
                            </div>
                        </div>

                        <CardContent className="p-4 space-y-3">
                            <div className="space-y-0.5">
                                <h3 className="text-xs font-semibold text-text-primary font-sans">{activeTab.title}</h3>
                                <p className="text-xs text-text-secondary font-sans leading-relaxed">{activeTab.desc}</p>
                            </div>

                            <div className="p-3 bg-bg rounded-[6px] transition-all">
                                {activeTab.renderPreview()}
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* 3-Bento Feature Row */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-8 text-left">
                    <Card className="bg-surface-raised rounded-[6px]">
                        <CardContent className="p-4 space-y-2">
                            <div className="h-8 w-8 rounded-[4px] bg-surface flex items-center justify-center text-text-primary mb-2">
                                <Webhook className="h-4 w-4 text-accent" />
                            </div>
                            <h3 className="text-sm font-semibold text-text-primary font-sans">Zero-Config Webhooks</h3>
                            <p className="text-xs text-text-secondary leading-relaxed font-sans">
                                Fires automatically on git push events with sub-7ms payload parsing and HMAC cryptographic verification.
                            </p>
                        </CardContent>
                    </Card>

                    <Card className="bg-surface-raised rounded-[6px]">
                        <CardContent className="p-4 space-y-2">
                            <div className="h-8 w-8 rounded-[4px] bg-surface flex items-center justify-center text-text-primary mb-2">
                                <Code2 className="h-4 w-4 text-accent" />
                            </div>
                            <h3 className="text-sm font-semibold text-text-primary font-sans">AST Fact Extraction</h3>
                            <p className="text-xs text-text-secondary leading-relaxed font-sans">
                                Deterministically parses Express routes, Mongoose schemas, and APIs before AI prompt synthesis to prevent hallucinations.
                            </p>
                        </CardContent>
                    </Card>

                    <Card className="bg-surface-raised rounded-[6px]">
                        <CardContent className="p-4 space-y-2">
                            <div className="h-8 w-8 rounded-[4px] bg-surface flex items-center justify-center text-text-primary mb-2">
                                <GitCommit className="h-4 w-4 text-accent" />
                            </div>
                            <h3 className="text-sm font-semibold text-text-primary font-sans">Auto README Sync</h3>
                            <p className="text-xs text-text-secondary leading-relaxed font-sans">
                                Commits clean, structured README markdown directly back to your default branch or pull request automatically.
                            </p>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </section>
    );
}
